Make sure pyhton version is not buggy 3.14.2
The default 3.14.2 causes a failure in typing annotations with sqlalchemy

TypeError: cannot use 'annotationlib.ForwardRef' as a set element (unhashable type: 'cell')